services:
  db:
    container_name: postgres_db

    # DONE:
    # define image (if our container is named postgres_db... i wonder... use 16 as the version.)
    image: postgres:16
    # define ports (postgres default port is 5432)
    ports:
      - "5432:5432"
    # define environment (POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB (can be found in the code)
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres

    # create and attach a volume to /var/lib/postgresql/data
    volumes:
      - somedata:/var/lib/postgresql/data


    # given: healthcheck
    # basically just checks that postgres is up and ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    # In case you were wondering, 
    # since we aren't specifying an image for app, we're telling it 
    # to look in the current directory for the build (from Dockerfile)
    build: .
    container_name: go_app
    # if our DB is not healthy
    # do not run
    depends_on:
      db:
        condition: service_healthy
      #DONE:
      # define environment variables
    environment:
            DB_HOST: "postgres_db"
            DB_PORT: "5432"
            DB_USER: "postgres"
            DB_PASSWORD: "postgres"
            DB_NAME: "postgres"
      # (DB_HOST (the name of the service our db is in)
      #, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME, 
      # and (this container's) PORT 8080)

    # DONE:
      # set our app to run on port 8080
    ports:
      - "8080:8080"


# DONE:
volumes:
    somedata:
# should be same name as the volume you defined for DB
